### ISSUE TITLE
OpenOCD init failed

### ISSUE THREAD

**Issue by jeremysykes** [ahessling/STM32F4Template#1]
Hi I realize this is likely an issue with openocd, but I wanted to share this and ask if I was using your repo correctly and see if you had any ideas on how to fix this issue. Here are the steps I took:

- Installed cmake, gnu arm tools and openocd
- Checked out the repo
- mv build.bat build.sh
- ./build.sh
- cd build
- make
- make flash

`[ 91%] Built target stm32f4xx
[100%] Built target STM32F4Template.elf
Open On-Chip Debugger 0.10.0
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Error: open failed
in procedure 'program'
in procedure 'init' called at file "embedded:startup.tcl", line 495
in procedure 'ocd_bouncer'
** OpenOCD init failed **
shutdown command invoked

make[3]: *** [src/CMakeFiles/flash] Error 1
make[2]: *** [src/CMakeFiles/flash.dir/all] Error 2
make[1]: *** [src/CMakeFiles/flash.dir/rule] Error 2
make: *** [flash] Error 2`

**Comment by ahessling** [comment]
Hi @jeremysykes,

the OpenOCD configuration strongly depends on the actual debugging hardware that is used. This configuration is made for a "first generation" ST-Link v2 device. Nowadays you find a revised version of the debugging hardware. In this case, try changing the reference to the debugging interface from

`interface/stlink-v2.cfg`

to

`interface/stlink-v2-1.cfg`

in the file tools/stm32f4discovery.cfg.

Of course if you have another debugging device, you have to adjust accordingly.

I hope this helps!

Kind regards,
André
