### ISSUE TITLE
no such instruction: `wfi' / `wfe'

### ISSUE THREAD

**Issue by adamvm** [ahessling/STM32F4Template#2]
I found such errors during building:

[ 53%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_iwdg.c.o
[ 55%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_lptim.c.o
[ 57%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_ltdc.c.o
[ 59%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_pwr.c.o
/home/adi/dev/STM32F4Template/lib/STM32F4xx_StdPeriph_Driver/inc/cmsis/core_cmInstr.h: Assembler messages:
/home/adi/dev/STM32F4Template/lib/STM32F4xx_StdPeriph_Driver/inc/cmsis/core_cmInstr.h:429: Error: no such instruction: `wfi'
/home/adi/dev/STM32F4Template/lib/STM32F4xx_StdPeriph_Driver/inc/cmsis/core_cmInstr.h:440: Error: no such instruction: `wfe'
/home/adi/dev/STM32F4Template/lib/STM32F4xx_StdPeriph_Driver/inc/cmsis/core_cmInstr.h:429: Error: no such instruction: `wfi'
make[2]: *** [lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/build.make:414: lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_pwr.c.o] Błąd 1
make[1]: *** [CMakeFiles/Makefile2:109: lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/all] Błąd 2
make: *** [Makefile:84: all] Błąd 2

**Comment by ahessling** [comment]
What toolchain are you using? What is the output of "arm-none-eabi-gcc --version"?

**Comment by adamvm** [comment]
arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]

**Comment by adamvm** [comment]
Built under  Linux

mkdir output && cd output && cmake .. && make

**Comment by ahessling** [comment]
Very strange, I just downloaded the current release 9-2019-q4-major (for Windows x86) and tried compiling. See the output down below (all looks well). Before that, I used 5.4-2016-q3 which also made no problems.

It seems that in your case, the inline assembler instructions (like wfi and wfe) don't work. Maybe if you try another version of the toolchain or compare the output of CMake to mine, there may be more clues.

`C:\Elektronik\Projekte\STM32F4Template>cd build   && cmake -G "Unix Makefiles" -D "CMAKE_TOOLCHAIN_FILE=../CMake/GNU-ARM-Toolchain.cmake" ../
Release build.
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/arm-none-eabi-gcc.exe
-- Check for working C compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/arm-none-eabi-gcc.exe
-- Check for working C compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/arm-none-eabi-gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/arm-none-eabi-g++.exe
-- Check for working CXX compiler: C:/Program Files (x86)/GNU Tools ARM Embedded/9 2019-q4-major/bin/arm-none-eabi-g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Elektronik/Projekte/STM32F4Template/build

C:\Elektronik\Projekte\STM32F4Template\build>make
Scanning dependencies of target stm32f4xx
[  2%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/misc.c.obj
[  4%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_adc.c.obj
[  6%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_can.c.obj
[  8%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_cec.c.obj
[ 10%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_crc.c.obj
[ 12%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_cryp.c.obj
[ 14%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_cryp_aes.c.obj
[ 17%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_cryp_des.c.obj
[ 19%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_cryp_tdes.c.obj
[ 21%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dac.c.obj
[ 23%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dbgmcu.c.obj
[ 25%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dcmi.c.obj
[ 27%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dma.c.obj
[ 29%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dma2d.c.obj
[ 31%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_dsi.c.obj
[ 34%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_exti.c.obj
[ 36%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_flash.c.obj
[ 38%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_flash_ramfunc.c.obj
[ 40%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_fmpi2c.c.obj
[ 42%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_gpio.c.obj
[ 44%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_hash.c.obj
[ 46%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_hash_md5.c.obj
[ 48%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_hash_sha1.c.obj
[ 51%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_i2c.c.obj
[ 53%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_iwdg.c.obj
[ 55%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_lptim.c.obj
[ 57%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_ltdc.c.obj
[ 59%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_pwr.c.obj
[ 61%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_qspi.c.obj
[ 63%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_rcc.c.obj
[ 65%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_rng.c.obj
[ 68%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_rtc.c.obj
[ 70%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_sai.c.obj
[ 72%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_sdio.c.obj
[ 74%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_spdifrx.c.obj
[ 76%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_spi.c.obj
[ 78%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_syscfg.c.obj
[ 80%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_tim.c.obj
[ 82%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_usart.c.obj
[ 85%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_wwdg.c.obj
[ 87%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/pure_virtual.c.obj
[ 89%] Building C object lib/STM32F4xx_StdPeriph_Driver/CMakeFiles/stm32f4xx.dir/src/stm32f4xx_fsmc.c.obj
[ 91%] Linking C static library libstm32f4xx.a
[ 91%] Built target stm32f4xx
Scanning dependencies of target STM32F4Template.elf
[ 93%] Building CXX object src/CMakeFiles/STM32F4Template.elf.dir/main.cpp.obj
[ 95%] Building C object src/CMakeFiles/STM32F4Template.elf.dir/system_stm32f4xx.c.obj
C:/Elektronik/Projekte/STM32F4Template/src/system_stm32f4xx.c: In function 'SetSysClock':
C:/Elektronik/Projekte/STM32F4Template/src/system_stm32f4xx.c:760:5: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
  760 |     while ((RCC->CFGR & (uint32_t)RCC_CFGR_SWS ) != RCC_CFGR_SWS_PLL);
      |     ^~~~~
C:/Elektronik/Projekte/STM32F4Template/src/system_stm32f4xx.c:761:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
  761 |     {
      |     ^
[ 97%] Building ASM object src/CMakeFiles/STM32F4Template.elf.dir/startup_stm32f40_41xxx.s.obj
[100%] Linking CXX executable STM32F4Template.elf
[100%] Built target STM32F4Template.elf
Scanning dependencies of target STM32F4Template.elf-size
   text    data     bss     dec     hex filename
   1100       8      28    1136     470 STM32F4Template.elf
[100%] Built target STM32F4Template.elf-size
Scanning dependencies of target STM32F4Template.lss
[100%] Built target STM32F4Template.lss
Scanning dependencies of target STM32F4Template.hex
[100%] Built target STM32F4Template.hex
Scanning dependencies of target STM32F4Template.bin
[100%] Built target STM32F4Template.bin
Scanning dependencies of target STM32F4Template
[100%] Built target STM32F4Template`

**Comment by adamvm** [comment]
[ 91%] Linking C static library libstm32f4xx.a
[ 91%] Built target stm32f4xx
Scanning dependencies of target STM32F4Template.elf
[ 93%] Building CXX object src/CMakeFiles/STM32F4Template.elf.dir/main.cpp.obj
[ 95%] Building C object src/CMakeFiles/STM32F4Template.elf.dir/system_stm32f4xx.c.obj
/home/adi/dev/STM32F4Template/src/system_stm32f4xx.c: In function 'SetSysClock':
/home/adi/dev/STM32F4Template/src/system_stm32f4xx.c:760:5: warning: this 'while' clause does not guard... [-Wmisleading-indentation]
     while ((RCC->CFGR & (uint32_t)RCC_CFGR_SWS ) != RCC_CFGR_SWS_PLL);
     ^~~~~
/home/adi/dev/STM32F4Template/src/system_stm32f4xx.c:761:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'while'
     {
     ^
[ 97%] Building ASM object src/CMakeFiles/STM32F4Template.elf.dir/startup_stm32f40_41xxx.s.obj
[100%] Linking CXX executable STM32F4Template.elf
[100%] Built target STM32F4Template.elf
Scanning dependencies of target STM32F4Template.bin
[100%] Built target STM32F4Template.bin
Scanning dependencies of target STM32F4Template.elf-size
   text    data     bss     dec     hex filename
   1196       8      28    1232     4d0 STM32F4Template.elf
[100%] Built target STM32F4Template.elf-size
Scanning dependencies of target STM32F4Template.lss
[100%] Built target STM32F4Template.lss
Scanning dependencies of target STM32F4Template.hex
[100%] Built target STM32F4Template.hex
Scanning dependencies of target STM32F4Template
[100%] Built target STM32F4Template

The key is: cmake -G "Unix Makefiles" -D "CMAKE_TOOLCHAIN_FILE=../CMake/GNU-ARM-Toolchain.cmake" ../

I use Ubuntu 20.04 LTS testing and often it updates packages but did not catch that any part of toolchain is updating
